//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeCV.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbMvcCvEntities1 : DbContext
    {
        public DbMvcCvEntities1()
            : base("name=DbMvcCvEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLABOUT> TBLABOUT { get; set; }
        public virtual DbSet<TBLAWARDS> TBLAWARDS { get; set; }
        public virtual DbSet<TBLEDUCATION> TBLEDUCATION { get; set; }
        public virtual DbSet<TBLEXPERIENCE> TBLEXPERIENCE { get; set; }
        public virtual DbSet<TBLINTERESTS> TBLINTERESTS { get; set; }
        public virtual DbSet<TBLKULLANIC> TBLKULLANIC { get; set; }
        public virtual DbSet<TBLSKILLS> TBLSKILLS { get; set; }
    }
}
